import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "@/lib/auth";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { ArrowLeft, Send, X, Loader2, UserPlus } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

const InviteFriend = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [note, setNote] = useState("");
  const [sending, setSending] = useState(false);

  // Fetch user's pending invites
  const { data: pendingInvites = [], isLoading } = useQuery({
    queryKey: ["my-invites", user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("invites")
        .select("*")
        .eq("inviter_id", user!.id)
        .eq("status", "pending")
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data || [];
    },
    enabled: !!user,
  });

  // Check if user is admin
  const { data: isAdmin } = useQuery({
    queryKey: ["is-admin", user?.id],
    queryFn: async () => {
      const { data } = await supabase.rpc("has_role", {
        _user_id: user!.id,
        _role: "admin",
      });
      return !!data;
    },
    enabled: !!user,
  });

  const canInvite = isAdmin || (pendingInvites.length < 5);

  const handleSendInvite = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user || !canInvite) return;

    const trimmedName = name.trim();
    const trimmedEmail = email.trim().toLowerCase();
    if (!trimmedName || !trimmedEmail) return;

    setSending(true);
    try {
      // Insert invite — token auto-generated by DB default
      const { data: invite, error } = await supabase
        .from("invites")
        .insert({
          inviter_id: user.id,
          invitee_email: trimmedEmail,
          invitee_name: trimmedName,
          personal_note: note.trim() || null,
        })
        .select()
        .single();

      if (error) throw error;

      // Get inviter's name for the email
      const { data: profile } = await supabase
        .from("profiles")
        .select("full_name, city")
        .eq("id", user.id)
        .single();

      // Send invite email
      await supabase.functions.invoke("send-transactional-email", {
        body: {
          templateName: "circle-invite",
          recipientEmail: trimmedEmail,
          idempotencyKey: `circle-invite-${invite.id}`,
          templateData: {
            inviterName: profile?.full_name || "A friend",
            inviteeName: trimmedName,
            personalNote: note.trim() || null,
            city: profile?.city || null,
            acceptUrl: `${window.location.origin}/accept-invite?token=${invite.token}`,
          },
        },
      });

      toast({ title: "Invitation sent!", description: `${trimmedName} will receive an email shortly.` });
      setName("");
      setEmail("");
      setNote("");
      queryClient.invalidateQueries({ queryKey: ["my-invites"] });
    } catch (err: any) {
      toast({ title: "Failed to send invite", description: err.message, variant: "destructive" });
    } finally {
      setSending(false);
    }
  };

  const handleRevoke = async (inviteId: string) => {
    try {
      const { error } = await supabase
        .from("invites")
        .update({ status: "revoked" as any })
        .eq("id", inviteId);
      if (error) throw error;
      queryClient.invalidateQueries({ queryKey: ["my-invites"] });
      toast({ title: "Invite revoked" });
    } catch (err: any) {
      toast({ title: "Failed", description: err.message, variant: "destructive" });
    }
  };

  return (
    <div className="min-h-screen bg-background pb-24">
      {/* Header */}
      <div className="border-b border-border bg-background/80 backdrop-blur-lg sticky top-0 z-20">
        <div className="mx-auto max-w-lg flex items-center gap-3 px-5 py-4">
          <button
            onClick={() => navigate(-1)}
            className="flex h-9 w-9 items-center justify-center rounded-full bg-card border border-border"
          >
            <ArrowLeft className="h-4 w-4 text-foreground" strokeWidth={1.5} />
          </button>
          <h1 className="font-display text-xl text-foreground">Invite a Friend</h1>
        </div>
      </div>

      <div className="mx-auto max-w-lg px-5 mt-6 space-y-8">
        {/* Invite form */}
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <h2 className="label-meta text-muted-foreground">Send an Invitation</h2>
            {!isAdmin && (
              <span className="label-meta text-muted-foreground">
                {5 - pendingInvites.length} of 5 remaining
              </span>
            )}
          </div>

          <form onSubmit={handleSendInvite} className="rounded-2xl border border-border bg-card p-5 space-y-4">
            <div className="space-y-2">
              <label className="label-meta text-muted-foreground">Friend's Name</label>
              <input
                type="text"
                required
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="Her full name"
                maxLength={100}
                className="w-full rounded-xl border border-border bg-background px-4 py-3 text-sm text-foreground placeholder:text-muted-foreground/60 focus:outline-none focus:ring-1 focus:ring-primary"
              />
            </div>

            <div className="space-y-2">
              <label className="label-meta text-muted-foreground">Email Address</label>
              <input
                type="email"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="her@email.com"
                maxLength={255}
                className="w-full rounded-xl border border-border bg-background px-4 py-3 text-sm text-foreground placeholder:text-muted-foreground/60 focus:outline-none focus:ring-1 focus:ring-primary"
              />
            </div>

            <div className="space-y-2">
              <label className="label-meta text-muted-foreground">Personal Note (Optional)</label>
              <textarea
                value={note}
                onChange={(e) => setNote(e.target.value)}
                placeholder="Add a personal message..."
                maxLength={500}
                rows={3}
                className="w-full rounded-xl border border-border bg-background px-4 py-3 text-sm text-foreground placeholder:text-muted-foreground/60 focus:outline-none focus:ring-1 focus:ring-primary resize-none"
              />
            </div>

            <button
              type="submit"
              disabled={sending || !canInvite}
              className="w-full rounded-full bg-primary py-3.5 transition-all hover:opacity-90 disabled:opacity-50 flex items-center justify-center gap-2"
            >
              {sending ? (
                <Loader2 className="h-4 w-4 text-primary-foreground animate-spin" />
              ) : (
                <Send className="h-4 w-4 text-primary-foreground" strokeWidth={1.5} />
              )}
              <span className="label-meta text-primary-foreground">
                {sending ? "Sending…" : "Send Invitation"}
              </span>
            </button>

            {!canInvite && !isAdmin && (
              <p className="text-xs text-muted-foreground text-center">
                You have 5 pending invites. Revoke one or wait for someone to accept.
              </p>
            )}
          </form>
        </div>

        {/* Pending invites */}
        <div className="space-y-3">
          <h2 className="label-meta text-muted-foreground">Pending Invitations</h2>
          {isLoading ? (
            <div className="rounded-2xl border border-border bg-card p-6 flex justify-center">
              <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
            </div>
          ) : pendingInvites.length === 0 ? (
            <div className="rounded-2xl border border-border bg-card p-6 text-center space-y-2">
              <UserPlus className="h-8 w-8 mx-auto text-muted-foreground/40" strokeWidth={1} />
              <p className="text-sm text-muted-foreground">No pending invites</p>
            </div>
          ) : (
            <div className="rounded-2xl border border-border bg-card divide-y divide-border">
              {pendingInvites.map((invite: any) => (
                <div key={invite.id} className="flex items-center gap-3 px-4 py-3.5">
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-foreground truncate">{invite.invitee_name}</p>
                    <p className="text-xs text-muted-foreground truncate">{invite.invitee_email}</p>
                  </div>
                  <button
                    onClick={() => handleRevoke(invite.id)}
                    className="flex h-7 w-7 items-center justify-center rounded-full hover:bg-secondary transition-colors"
                  >
                    <X className="h-3.5 w-3.5 text-muted-foreground" strokeWidth={1.5} />
                  </button>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default InviteFriend;
